name: clang-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: install tools
      run: |
        sudo apt update
        sudo apt install clang-format
        git config --global user.email "octocat@example.com"
        git config --global user.name "octocat"
    - name: refactor
      run: |
        clang-format -i -style=file main.cpp
        
    - name: git setting
      run: |
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Commit and Push
      run: |
        git add .
        git commit -m "auto commit" -a
        git pull
        git push origin main
