name: clang-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: install tools
      run: |
        sudo apt update
        sudo apt install clang-format
        git config --global user.email "octocat@example.com"
        git config --global user.name "octocat"
    - name: refactor
      run: |
        clang-format -i -style=file main.cpp
    - name: push
      run: |
#         git remote rm origin
#         git remote add origin git@github.com:surpace0924/coding_style_check_test.git
#         git remote origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        if (git diff --shortstat | grep '[0-9]'); then \
          git add .; \
          git commit -m "GitHub Actions から差分を Push"; \
          git push origin HEAD:${GITHUB_REF}; \
        fi
