name: clang-format CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    
    - name: install tools
      run: |
        sudo apt update
        sudo apt install clang-format
  
    - name: clang format
      run: |
        find include src examples -name *.c -o -name *.cc -o -name *.cpp -o -name *.h -o -name *.hh -o -name *.hpp | xargs clang-format -i -style=file --verbose
        
    - name: git setting
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config pull.rebase false
        
    - name: Commit and Push
      run: |
        git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        if (git diff --shortstat | grep '[0-9]'); then \
          git add .; \
          git commit -m "[CI] Automatically apply clang-format"; \
          git push origin HEAD:dev; \
        fi